import "../_dnt.polyfills.js";
import "../_dnt.polyfills.js";
import { IEnvironment, IEnvironmentPath, IEnvironmentVariables } from './interfaces.js';
import { IRuntimeEnvironment, IVersion, OsFamily, Runtime, RuntimeArch, runtimeInfo } from '../runtime/mod.js';
import { chdir, commandLine, commandLineArgs, cwd, exit, getExitCode, newLine, processId, setExitCode } from './process.js';
import { EnvironmentVariables, envVars } from './variables.js';
import { EnvironmentPath, envPath } from './path.js';
export * from './interfaces.js';
declare const userKey: string;
declare const machineNameKey: string;
declare const userDomainKey: string;
export declare class Environment implements IEnvironment {
    #private;
    constructor(envVars: IEnvironmentVariables, envPath: IEnvironmentPath);
    get userInteractive(): boolean;
    set userInteractive(value: boolean);
    get vars(): IEnvironmentVariables;
    get newLine(): string;
    get is64BitProcess(): boolean;
    get os(): OsFamily;
    get arch(): RuntimeArch;
    get runtimeName(): Runtime;
    get runtime(): IRuntimeEnvironment;
    get deno(): boolean;
    get node(): boolean;
    get browser(): boolean;
    get processId(): number;
    get machineName(): string;
    get userName(): string;
    get userDomainName(): string;
    get isCi(): boolean;
    get ciName(): string | undefined;
    get exitCode(): number;
    set exitCode(value: number);
    get commandLine(): string;
    get commandLineArgs(): string[];
    get currentDirectory(): string;
    set currentDirectory(value: string);
    get version(): IVersion;
    get path(): IEnvironmentPath;
    expand(value: string): string;
    has(name: string): boolean;
    get(name: string): string | undefined;
    set(name: string, value: string, isSecret?: boolean): void;
    delete(name: string): void;
    exit(code?: number): void;
}
export declare const env: Environment;
export { chdir, commandLine, commandLineArgs, cwd, EnvironmentPath, EnvironmentVariables, envPath, envVars, exit, getExitCode, machineNameKey, newLine, processId, runtimeInfo, setExitCode, userDomainKey, userKey, };
