import { Browser, Engine, globalScope, IRuntimeEnvironment, IVersion, OsFamily, Runtime, RuntimeArch, Version } from './base.browser.js';
export type { Browser, Engine, IRuntimeEnvironment, IVersion, OsFamily, Runtime, RuntimeArch };
export { globalScope, Version };
export declare const DEBUG: boolean;
export declare const TRACE: boolean;
export declare const runtimeInfo: IRuntimeEnvironment;
export declare const isDeno: boolean;
export declare const isNode: boolean;
export declare const isBrowser: boolean;
export declare const isWindows: boolean;
export declare const isDarwin: boolean;
export declare const isLinux: boolean;
export declare const isMobile: boolean;
