"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VERSION = exports.fail = exports.assertThrows = exports.assertRejects = exports.assertNotStrictEquals = exports.assertStrictEquals = exports.assertArrayIncludes = exports.assertStringIncludes = exports.assertNotMatch = exports.assertMatch = exports.assertInstanceOf = exports.assertFalse = exports.assertExists = exports.assertAlmostEquals = exports.assertNotEquals = exports.assertEquals = exports.assert = void 0;
var asserts_js_1 = require("./deps/deno.land/std@0.148.0/testing/asserts.js");
Object.defineProperty(exports, "assert", { enumerable: true, get: function () { return asserts_js_1.assert; } });
Object.defineProperty(exports, "assertEquals", { enumerable: true, get: function () { return asserts_js_1.assertEquals; } });
Object.defineProperty(exports, "assertNotEquals", { enumerable: true, get: function () { return asserts_js_1.assertNotEquals; } });
Object.defineProperty(exports, "assertAlmostEquals", { enumerable: true, get: function () { return asserts_js_1.assertAlmostEquals; } });
Object.defineProperty(exports, "assertExists", { enumerable: true, get: function () { return asserts_js_1.assertExists; } });
Object.defineProperty(exports, "assertFalse", { enumerable: true, get: function () { return asserts_js_1.assertFalse; } });
Object.defineProperty(exports, "assertInstanceOf", { enumerable: true, get: function () { return asserts_js_1.assertInstanceOf; } });
Object.defineProperty(exports, "assertMatch", { enumerable: true, get: function () { return asserts_js_1.assertMatch; } });
Object.defineProperty(exports, "assertNotMatch", { enumerable: true, get: function () { return asserts_js_1.assertNotMatch; } });
Object.defineProperty(exports, "assertStringIncludes", { enumerable: true, get: function () { return asserts_js_1.assertStringIncludes; } });
Object.defineProperty(exports, "assertArrayIncludes", { enumerable: true, get: function () { return asserts_js_1.assertArrayIncludes; } });
Object.defineProperty(exports, "assertStrictEquals", { enumerable: true, get: function () { return asserts_js_1.assertStrictEquals; } });
Object.defineProperty(exports, "assertNotStrictEquals", { enumerable: true, get: function () { return asserts_js_1.assertNotStrictEquals; } });
Object.defineProperty(exports, "assertRejects", { enumerable: true, get: function () { return asserts_js_1.assertRejects; } });
Object.defineProperty(exports, "assertThrows", { enumerable: true, get: function () { return asserts_js_1.assertThrows; } });
Object.defineProperty(exports, "fail", { enumerable: true, get: function () { return asserts_js_1.fail; } });
exports.VERSION = '0.0.1';
//# sourceMappingURL=deps.js.map