import "../_dnt.polyfills.js";
import { Version } from './version.js';
import { globalScope } from './global.js';
import type { IRuntimeEnvironment } from './interfaces.js';
export * from './semantic-version.js';
export * from './interfaces.js';
export { Version, globalScope };
export declare const runtimeInfo: IRuntimeEnvironment;
export declare const isDeno: boolean;
export declare const isNode: boolean;
export declare const isBrowser: boolean;
export declare const isWindows: boolean;
export declare const isDarwin: boolean;
export declare const isLinux: boolean;
export declare const isMobile: boolean;
