export {
    assert,
    assertAlmostEquals,
    assertArrayIncludes,
    assertEquals,
    assertExists,
    assertFalse,
    assertInstanceOf,
    assertMatch,
    assertNotEquals,
    assertNotMatch,
    assertNotStrictEquals,
    assertRejects,
    assertStrictEquals,
    assertStringIncludes,
    assertThrows,
    fail,
} from 'https://deno.land/std@$STD_VERSION/testing/asserts.ts';
